version: '3.8'

services:
  # Oracle Database (using free Oracle Express Edition)
  oracle-db:
    image: gvenzl/oracle-xe:latest
    environment:
      ORACLE_PASSWORD: oracle123
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/oracle123@localhost:1521/XE", "as", "sysdba", "select 1 from dual"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521:XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      oracle-db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    depends_on:
      - backend

volumes:
  oracle-data:
